name: latest_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-255.2.beta <3.0.0'

dependencies:
  csv: ^5.0.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_svg: ^1.1.6
  location: ^4.4.0
  mobile_scanner: ^2.1.0
  objectbox: ^1.6.2
  objectbox_flutter_libs: any
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  spreadsheet_decoder: ^2.1.1
  syncfusion_flutter_xlsio: ^20.3.58-beta

dev_dependencies:

  build_runner: ^2.0.0

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  objectbox_generator: any

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
